### ISSUE TITLE
Precompile support

### ISSUE THREAD

**Issue by axic** [primea/js-primea-hypervisor#14]
If it is desired to run Solidity contracts, the VM needs to support precompiles, especially the identity contract.

Implement the precompiles in WASM:
- [x] ecrecover
- [x] sha256
- [x] ripemd160
- [x] identity

**Comment by wanderer** [comment]
@axic is this done now?

**Comment by axic** [comment]
So I'll need to upload my new repo _ewasm-precompiles_ which has the C sources as well as the WASTs. We can either take the WASTs or use that repo as a submodule here.
